### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by A16D** [Victor-IX/NodeEditorSwitcher#1]
Running on Blender 4.1.0

Installation Error  - ZIP packaged incorrectly; __init__.py should be in a directory, not at top-level

**Comment by Victor-IX** [comment]
The **1.0.2 version** is only working with **Blender 4.2** with the new [Extension experimental feature](https://extensions.blender.org) and can be directly downloaded from Blender [Node Editor Switcher Extension](https://extensions.blender.org/add-ons/node-editor-switcher/). If you want to use this addon with **other versions of Blender**, you can download the [Version 1.0.1](https://github.com/Victor-IX/NodeEditorSwitcher/releases/tag/v1.0.1).

I will update the readme and add a note on the 1.0.2 version
