### ISSUE TITLE
Suggestion: Move Quick Access Buttons

### ISSUE THREAD

**Issue by venomgfx** [Victor-IX/NodeEditorSwitcher#2]
Hi! Love this add-on, one of the first extensions I always enable.

I think the Quick Access Buttons should be on the left side, because they are sub-modes of the Node Editor. Also when the header doesn't fit they will still be visible.

You can test it by changing `bpy.types.NODE_HT_header.append` to `bpy.types.NODE_HT_header.prepend`.

https://github.com/Victor-IX/NodeEditorSwitcher/blob/71745c3e62c8346f5351caf038f401b6f8177474/source/__init__.py#L232

Yes they will be a bit redundant when in the Shader Editor because the type selector is also there, but for Compositor and GeoNodes it should be okay.

Thanks!

**Comment by Victor-IX** [comment]
Thanks for the suggestion! 
A new version with customizable button placement has been released
