### ISSUE TITLE
Pie menu for work Modes please

### ISSUE THREAD

**Issue by slrgt** [Victor-IX/NodeEditorSwitcher#3]
Hi, I love your addon and it would be amazing if it would also create a pie menu when clicking Tab to switch between Edit Mode, Object Mode, Pose Mode, Weight Paint Mode, etc and to switch between Face, Vertex, and Edge Mode too. Something similar to this old addon: 

![image](https://github.com/user-attachments/assets/5569def4-76c4-45b3-96af-9b8f8ccb9d86)

**Comment by Victor-IX** [comment]
Thanks for the proposal. This add-on will only focus on the different node editors of Blender. I want to keep it easy to use without too many options.

In the future, I plan to create other useful pie menus, so I'll keep your idea for a future extension! The only concern I have is that the pie menu you show here probably comes from Machin3Tool. I don't know if remaking this part of the add-on as a standalone free tool will be accepted by Machin3. I can definitely ask him.

**Comment by slrgt** [comment]
Ok thanks please ask him, I asked if he could make a free standalone version of the pie menu but he said he’s too busy
