### ISSUE TITLE
Suggestion: Customize switcher + make buttons dissapear.

### ISSUE THREAD

**Issue by Gioni05** [Victor-IX/NodeEditorSwitcher#4]
Hello,

I really like this addon, it's very useful but i have some small suggestions that will make it so much powerful.

First of all it will be great when i uncheck one of the 4 hotkeys, the corresponding editor button to disappear from the quick acces buttons from the top. because if don't want to use those buttons they are wasting space. 
![image](https://github.com/user-attachments/assets/faea95c8-94a9-49a6-98e7-fb4e9c63eb23)

Second, it will be nice if i can choose what editor it's in the list. Because i don't really use the compositor % geometry editor. I usually toggle very often between Shader, World and UV for example and being able to customize the editor included in the switcher will make this perfect. 

![image](https://github.com/user-attachments/assets/67c999b5-0cb5-4820-94be-c2e2f4a413bf)

Thank You!

**Comment by Victor-IX** [comment]
I have already started working on that, and the first feature request will be available in the next update.
For the second one, it's not really the intent of this add-on; it's supposed to be simple to use with low setup requirements and focused on the node editor only.
I might eventually create a new add-on with extended customization that can support all the Blender editors.
